version = 0.1

[default.deploy.parameters]
stack_name = "new-fbp"
resolve_s3 = true
s3_prefix = "new-fbp"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "FBPUsersTableName=\"FBPUsers\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
